name: Trading Automation

on:
  schedule:
    # Every 5 minutes from 9:15 to 3:30 IST (3:45–10:00 UTC)
    - cron: "*/5 3-9 * * 1-5"
    - cron: "0 10 * * 1-5"
  workflow_dispatch:

jobs:
  run-trade:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run trading script
        run: python src/daily_recommender_once.py

      - name: Upload signals
        uses: actions/upload-artifact@v3
        with:
          name: trade-signals
          path: output/live_trade_signals.json
