name: Trading Automation

on:
  schedule:
    # Run every 5 minutes, Monday-Friday, from 03:45 to 10:00 UTC (9:15 to 15:30 IST)
    - cron: "*/5 3-9 * * 1-5"
    - cron: "0 10 * * 1-5"
  workflow_dispatch:   # allows manual run

jobs:
  run-trade:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run trading script
        run: python src/daily_recommender_once.py

      - name: Upload signals
        uses: actions/upload-artifact@v3
        with:
          name: trade-signals
          path: output/live_trade_signals.json
